- .travis.yml
- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/docker-compose.full.yml
- {{cookiecutter.project_shortname}}/docker-services.yml
- {{cookiecutter.project_shortname}}/invenio.cfg
- {{cookiecutter.project_shortname}}/scripts/bootstrap
Partially addresses https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/11 since it uses the invenio.cfg file only for the `dev` environment. Mainly due to the lack of distinction between `localhots` or named hosts in the docker network such as `mq`, `es`, etc.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/23
> WIP: config: use cfg file instead of env in docker-services

- {{cookiecutter.project_shortname}}/Pipfile
Changes:
* Pin versions in order to keep working on the December release.
> dependencies: pin rdm dependencies for v1.0.0a3

- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/invenio.cfg
Changes:
- Does not copy the logo on the Dockerfile. Delegates to the collect/webpack build. This breaks the `update` command of the CLI see https://github.com/inveniosoftware/invenio-cli/issues/73.
Closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/26
@fenekku What is your take on it, shall we break `update` or keep it hardcoded for now and fix it for January?
> customization: remove logo name and format dependency

- {{cookiecutter.project_shortname}}/Pipfile
Because we have to run pipenv install --pre until we move
to non-alpha versions, we are subject to the breaking changes
introduced by pre dependencies.
In this case, werkzeug 1.0.0RC1 changes the import of ImmutableDict:
from: `from werkzeug import ImmutableDict`
to: `from werkzeug.datastructures import ImmutableDict` which breaks
flask-babel, which breaks us.
> dependencies: limit werkzeug <1.0.0 [why]

- scripts/wait-for-services.sh
- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/invenio.cfg
Places relatively sane defaults for Content-Security-Policy
in invenio.cfg to allow pdfs preview + allow developers to
add their own after.
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/53
Removes webpack calls to create assets and statics bc
invenio-cli takes care of it:
* don't want redundancy since expensive operation
* invenio-cli takes care of it because it can
then dynamically choose not to re-install JS
dependencies: speeding it up further.
> Inveniocfg dockerfile

- {{cookiecutter.project_shortname}}/Pipfile
Changes:
* Updates RDM packages
* Bump marshmallow
* Remove Werkzeug pin since it was fixed :)
Requries: https://github.com/inveniosoftware/invenio-rdm-records/pull/60
Requires: https://github.com/inveniosoftware/invenio-app-rdm/pull/77
Closes: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/40
> dependencies: update rdm packages, marshmallow, and werkzeug issues

- {{cookiecutter.project_shortname}}/Pipfile
**WARNING**: Don't delete the branch when merging since we are using it in `invenio-cli`.
This change is an example of the web of dependency problem and a small-scale solution (and an example of a fortuitous workaround, but it's really a side note - see below):
Because we are strictly pinning (`==`) versions in the Pipfile of the cookiecutter, whenever a bugfix from another module is required, we need to change this file. Even then, if someone already ran the cookiecutter, they won't get that fix because their Pipfile is already cut.
What I suggest: loosen the version pinning in the Pipfile to at least allow patches, e.g.,:
`invenio-rdm-records = "==0.9.0"` => `invenio-rdm-records = "~=0.9.0"`
A new monthly release would just bump the `X` in `"~=0.X.0"` (I think @slint mentioned something …
> dependencies: make patch release compatible

- scripts/bootstrap
- {{cookiecutter.project_shortname}}/Dockerfile
Closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/54
Building the assets when running `containerize` is not desired since it is time consuming and it will happen twice. However, when deploying in the "cloud" they are needed. Therefore, this PR allows it conditionally. This way docker-compose will not pass the arg and `containerize` stays as is.
This is part of a bigger picture solution mentioned in the above issue.
**Method 1: flag the docker build and launch a job**
Since we do not want to incur into the "double building" of assets
(Once in the docker build, a second if updating). One option could
be to flag the building of assets in the Dockerfile (e.g. build only
if `include_assets` env var is True or is set).
Since as per docker documentation, when a volume is …
> docker: add alt assets inclusion during build

- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/app_data/README.md
Adds a `app_data/` folder in the project to hold the custom application data files like vocabulary files (in `app_data/vocabularies`). This is general enough to hold all other cases of files holding application data.
Needed in particular for `invenio-cli containerize` to work with custom vocabulary.
> dockerfile: copy app_data/ folder

- {{cookiecutter.project_shortname}}/Pipfile
Requires https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/62
closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/63
> dependencies: bump app-rdm and rdm-records for release 0.7.0

- {{cookiecutter.project_shortname}}/Pipfile
Until the WTForms [`email-validator` extra](https://github.com/wtforms/wtforms/pull/429) is installed upstream (https://github.com/lepture/flask-wtf and/or https://github.com/mattupstate/flask-security (don't know the status of that repo too much?)), we cap the version of wtforms so not to break.
> dependencies: cap wtforms until fixed upstream

- {{cookiecutter.project_shortname}}/Pipfile
closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/67
@fenekku `invenio-accounts` v1.2.1 and v1.1.4 have been released. Both include the `email-validator` dependency. According to our `invenio` dependency we should be in v1.1.4.
> dependencies: unpin wtforms

- cookiecutter.json
~~Requires: https://github.com/inveniosoftware/invenio-cli/pull/123~~ Comes from upstream cookiecutter.
Sample result:
```
% cookiecutter ../cookiecutter-invenio-rdm 
project_name [My Site]: Pablo's version
project_shortname [pablo-s-version]: 
project_site [pablo-s-version.com]: 
github_repo [pablo-s-version/pablo-s-version]: 
description [Invenio RDM Pablo's version Instance]: 
author_name [CERN]: 
author_email [info@pablo-s-version.com]: 
```
Closes: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/45
> config: load slugify extension and use for project_shortname

- cookiecutter.json
- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/invenio.cfg
**Changes:**
- adds support for python 3.7 and 3.8 (untested)
- sets `THEME_LOGO` to that of InvenioRDM. This value is already set in `invenio-app-rdm` and would not be needed. However, for clarity to the user it is better to leave the variable in `invenio.cfg`.
Note: Python 3.7 is development only because the Dockerfile of Invenio only exists for 3.6. However, I have tested it in local with Python 3.7 (followed the development part and it works).
Closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/71
Closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/64
> add support for python 3.7

- {{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf
- {{cookiecutter.project_shortname}}/docker/nginx/nginx.conf
[Nginx_Warnings](https://github.com/inveniosoftware/invenio-app-rdm/issues/91)
According to nginx documentation, the ```ssl``` directive is deprecated and ```ssl on``` is no longer required.  ```listen 443 ssl``` is enough.
Also for the option ```gzip_types```, the mime-type ```text/html``` is always included by default, so no need to specify it explicitly.
> warnings_fix

- {{cookiecutter.project_shortname}}/Pipfile
- Moves invenio-s3 extension into invenio-app-rdm as an extra
requirement.
> installation: move invenio-s3 extension to app

- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/Pipfile
Here are two fixes so that the cookiecutter project will work once a Python 3.8 base docker image is published, as proposed in inveniosoftware/docker-invenio#32.
> Python 3.8 fixes

- {{cookiecutter.project_shortname}}/Pipfile
This should fail until you release invenio-app-rdm 0.11.X @ppanero , but it sets everything up in advance. :runner:
> dependencies: bump invenio-app-rdm to ~=0.11.0

- {{cookiecutter.project_shortname}}/Pipfile
- {{cookiecutter.project_shortname}}/invenio.cfg
- Add SERVER_HOSTNAME to invenio.cfg in order to pass
same origin policy
This is part of making a working August release and will be merged and deployed when it passes.
> global: bump dependencies and add config [more]

- cookiecutter.json
- Makes 3.7 the default option. By default the first option is the default, and can only be overwritten with a [user config file](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/choice_variables.html). Thus it seems the easiest simply to change the order.
> cookiecutter: make python 3.7 the default option

- {{cookiecutter.project_shortname}}/Dockerfile
- {{cookiecutter.project_shortname}}/docker-compose.full.yml
- {{cookiecutter.project_shortname}}/docker-services.yml
Related to https://github.com/inveniosoftware/docker-services-cli/pull/13
**Changes**
- Change the restart: always from docker-services.yml in Cookiecutter-Invenio-RDM. Might need another pass when a decision is taken in inveniosoftware/docker-services-cli#13
- Remove unused services from docker-services.yml: flower, kibana, lb. Some of them like `lb` were even missing files (haproxy docker file) and resulting in  errors upon `docker-compose exec` commands.
> docker-services: remove unused and change restart policy

- {{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_rest.ini
- {{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_ui.ini
For the longest time, the default installation at Northwestern
would return 502s to some people at some times... Turns out that
headers larger than 4096 bytes were sometimes generated causing
uwsgi to drop the request. While not going overboard, this does
give us some room to spare for larger headers.
I am sharing the fix here, because we are probably not the only ones 
that would experience this with an out of the gate install.
> uwsgi: fix occasional 502 by boosting buffer-size [+]

- {{cookiecutter.project_shortname}}/Pipfile
- Invenio 3.4
- Update RDM patch versions
- Remove nbconvert since it was capped in invenio-previewer
> dependencies: use invenio 3.4

- {{cookiecutter.project_shortname}}/docker-services.yml
There is a restart policy for other services. Why not for app? ¯\_(ツ)_/¯
> docker-compose: add restart policy for app

- cookiecutter.json
- {{cookiecutter.project_shortname}}/docker-compose.full.yml
- {{cookiecutter.project_shortname}}/docker-compose.yml
As per https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/16 removes sqlite as offered  db option and removes the conditional blocks in the templates that checked for sqlite.
> Remove sqlite as an option and related conditional blocks

- {{cookiecutter.project_shortname}}/docker-compose.full.yml
restart: unless-stopped is a bit more UX friendly than always
fixes an issue raised by chriz on discord
> docker-compose: make worker restart policy same as others

- {{cookiecutter.project_shortname}}/Dockerfile
closes #162 
`ImageMagick` dependency has been moved to the inveniosoftware base image https://github.com/inveniosoftware/docker-invenio/pull/45
> dockerfile: remove imagemagick dependency

- cookiecutter.json
- {{cookiecutter.project_shortname}}/docker-compose.full.yml
- {{cookiecutter.project_shortname}}/docker-compose.yml
- {{cookiecutter.project_shortname}}/docker-services.yml
closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/126
**Important note**: PgAdmin requires `db` as host name to connect properly
screenshots (pgadmin, phpmyadmin, flower, kibana)
> global: add development services

- hooks/post_gen_project.sh
- scripts/setup
- {{cookiecutter.project_shortname}}/.gitignore
- {{cookiecutter.project_shortname}}/docker-services.yml
* When using S3 (min.io) for local testing, create a directory that will
be used as default bucket for the files location instead of creating a
bucket programmatically with ``mc``. (closes #53)
> setup: create S3 bucket from preexisting directory

- {{cookiecutter.project_shortname}}/docker-services.yml
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1031
File upload:
File preview:
Object in minio:
> services: configure secrets/user for minio (s3)

- {{cookiecutter.project_shortname}}/docker-services.yml
- {{cookiecutter.project_shortname}}/docker/pgadmin/servers.json
* closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/192
Server is correctly configured but when accessing for the first time it's still asking for the password. Not sure why .... Maybe someone has a better understanding about this.
> pgadmin: Add servers

- {{cookiecutter.project_shortname}}/docker-compose.full.yml
Since there was no tag, the image was build for every service that uses it (web-api, web-ui and worker), beeing cached only until the webpack part.
> compose: build instance/app image only once

- {{cookiecutter.project_shortname}}/Pipfile
* ipython 8.1.0 introduced an issue when running python<3.9
> global: skip ipython 8.1.0

- cookiecutter.json
* Python 3.6 have reached end-of-life and is no longer supported
by the Python foundation.
> global: remove python 3.6 as an install option

- {{cookiecutter.project_shortname}}/Pipfile
celery 5.2.4 got released (latests 5.2.6) and also ipython 8.2.0.
Tried installing with invenio-app-rdm 9.0.0.dev11 and it worked (took 2 minutes):
```
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 214/214 — 00:02:27
```
Also removing the setuptools pin shows a deprecation warning that might hit us later on...
```
/.../instance-members/lib/python3.8/site-packages/setuptools/config/__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.read_configuration` became deprecated.
For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the future.
warnings.warn(dedent(msg), SetuptoolsDeprecationWarning)
```
> remove ipython and setuptools restriction

- {{cookiecutter.project_shortname}}/invenio.cfg
set a default value for the flask variable `SEND_FILE_MAX_AGE_DEFAULT` 
partly closes https://github.com/inveniosoftware/invenio-communities/issues/718
> config: add default value for caching max_age

- {{cookiecutter.project_shortname}}/invenio.cfg
- closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/227
When deploying the demo site in QA for custom fields. I realized that it did not supported prefixed indices (happened also in the previous release... To avoid noticing this at deploy time, we can add the prefix to every instance (it has no impact on the end user). 
P.S. Approved by Lars
> config: prefix indices

- {{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_ui.ini
The uWSGI UI application server is in charge of serving files. Without this setting serving large files was failing for us, ergo it might be useful for others. The option is already used in the uWSGI API application server. See https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html?highlight=wsgi-disable-file-wrapper#things-to-know-best-practices-and-issues-read-it for more details.
> uwsgi: disable file wrapper causing issues

- {{cookiecutter.project_shortname}}/app_data/vocabularies.yaml
Using the `affiliations_ror.yaml` broke the `invenio-cli services setup`, because the expected layout in the `vocabularies.yaml` has shifted in https://github.com/inveniosoftware/invenio-rdm-records/commit/e3df51f5a9f25c20a4234e0d6e524c8d021d8fd2
> vocabularies: chase change in rdm-records fixtures command

- {{cookiecutter.project_shortname}}/app_data/vocabularies.yaml
This removes the fixtured affiliations vocabulary now that datastreams are available as well as the outdated ror yaml file. To be merged only when https://github.com/inveniosoftware/invenio-vocabularies/pull/327 and https://github.com/inveniosoftware/invenio-app-rdm/pull/2680 are released.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> vocabularies: switch to datastreams for affiliations

- {{cookiecutter.project_shortname}}/docker-services.yml
Newer versions of Minio drop support for MinIO Gateway and the related filesystem mode. 
From the documentation (https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html)
> Deployments still using the standalone or filesystem MinIO modes that upgrade to [RELEASE.2022-10-29T06-21-33Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-10-29T06-21-33Z) or later receive an error when attempting to start MinIO. 
> 
> Important
> 
> Standalone/file system mode continues to work on any release up to and including [RELEASE.2022-10-24T18-35-07Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-10-24T18-35-07Z). To continue using a standalone deployment, install that MinIO release or any [earlier release](https://github.com/minio/minio/releases).
If …
> docker: pin minio version to avoid fs errors

- {{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf
Enabling `chunked_transfer_encoding` (HTTP/1.1) force-enables request buffering, cf: http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_request_buffering
> nginx: disable chunked transfer encoding for proxied apps

- {{cookiecutter.project_shortname}}/docker/nginx/nginx.conf
Otherwise, `nginx` may fall back to using "application/octet-stream" which browsers may not like.
For instance, `pdfjs-dist` v4 uses `mjs` files, which is used by the new PDF previewer in `Invenio-Previewer`.
The files are transferred correctly, but because the files are reported to have the wrong MIME type they can get blocked by the browser.
This PR tells `nginx` that `mjs` files are, like `js` files, to be reported as `application/javascript`.
> nginx: add "application/javascript" MIME type for mjs files

- {{cookiecutter.project_shortname}}/invenio.cfg
* Configures CSP policy to allow for WASM-based web workers
* Required  by https://github.com/inveniosoftware/invenio-rdm-records/pull/2065
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …
> Allow WASM-based web workers in CSP policy

- {{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf
* With the addition of the new Invenio-Sitemap module, the ``robots.txt`` file is no longer static, it's a template.
Check https://github.com/inveniosoftware/invenio-app-rdm/commit/6a0bd02892b7ba9feaa5a159a8dfb0f66e288ae8#diff-f842f0243e36637687a93857155ca64bd0f8b594394e19d1fb85f30b062ad558
> nginx: remove robots.txt static location
