inveniosoftware/cookiecutter-invenio-rdm

{{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_rest.ini
See this obscure option to fix send_file breaking
https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.12.html#wsgi-disable-file-wrapper
=> uwsgi: fix send_file error [more]

{{cookiecutter.project_shortname}}/.dockerignore, {{cookiecutter.project_shortname}}/Dockerfile, {{cookiecutter.project_shortname}}/templates/.gitkeep
=> templates: add templates folder

.travis.yml, {{cookiecutter.project_shortname}}/.gitignore
closes #55
This should then be merged into v0.7.0 . I am treating https://github.com/inveniosoftware/invenio-cli/issues/121 as a bug and making the fixes go to the march release. A dependency problem also needed to be fixed anyway.
=> global: add .gitignore to cookiecutter

{{cookiecutter.project_shortname}}/Pipfile, {{cookiecutter.project_shortname}}/assets/less/site/globals/site.overrides, {{cookiecutter.project_shortname}}/assets/less/site/globals/site.variables, {{cookiecutter.project_shortname}}/assets/less/theme.config, {{cookiecutter.project_shortname}}/assets/less/theme.less, {{cookiecutter.project_shortname}}/assets/less/variables.less
Based on https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/236/files
Requires merge and release of https://github.com/inveniosoftware/invenio-app-rdm/pull/135
Closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/75
=> semantic-ui theming

{{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_rest.ini, {{cookiecutter.project_shortname}}/docker/uwsgi/uwsgi_ui.ini
Temporary fix. See https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/89
=> uwsgi: force single interpreter

{{cookiecutter.project_shortname}}/Pipfile
keeping you in the loop via reviewers but will merge this and put it on the v0.10.0 branch immediately.
=> dependencies: bump invenio-app-rdm to ~=0.10.0

{{cookiecutter.project_shortname}}/invenio.cfg
requires, but is not blocked by https://github.com/inveniosoftware/invenio-app-rdm/pull/229
=> i18n: add translations dropdown with turkish

{{cookiecutter.project_shortname}}/static/images/invenio-rdm.svg
* closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/103
=> style: Update logo to delete blank spaces

{{cookiecutter.project_shortname}}/invenio.cfg
As I deploy our instance for real, I will be going through the steps someone new will and so I will try to improve things as I go. Here I am improving the `invenio.cfg`
=> config: improve invenio.cfg documentation

{{cookiecutter.project_shortname}}/invenio.cfg
Requires https://github.com/inveniosoftware/invenio-records-resources/pull/137
=> config: change hostname variable name

{{cookiecutter.project_shortname}}/Pipfile
[skip ci] 
Minor bumps, for showcase purposes for now it should not be needed we can bump in bulk once all required are merged and released.
**Cancelled travis, skip ci did not work...**
=> dependencies: minor bumps records-resources, rdm-records, app-rdm

{{cookiecutter.project_shortname}}/assets/less/theme.config
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/515
=> theme: set grid to invenio theme

{{cookiecutter.project_shortname}}/assets/less/theme.config
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/546
=> theme: set rdm theme

{{cookiecutter.project_shortname}}/docker-services.yml
=> Upgrade to rabbitmq 3.8

{{cookiecutter.project_shortname}}/invenio.cfg
closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/151
=> config: disable DataCite DOI

{{cookiecutter.project_shortname}}/Dockerfile
=> dockerfile: add imagemagick binary

cookiecutter.json
closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/176
=> cookiecutter: remove mysql from db options

{{cookiecutter.project_shortname}}/invenio.cfg
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/782
=> configuration: remove SITE_HOSTNAME

{{cookiecutter.project_shortname}}/docker-compose.full.yml, {{cookiecutter.project_shortname}}/docker-compose.yml, {{cookiecutter.project_shortname}}/docker-services.yml
* closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/177
=> docker-services: remove flower

{{cookiecutter.project_shortname}}/invenio.cfg
=> config: set OAI id prefix

{{cookiecutter.project_shortname}}/assets/less/site/globals/site.overrides
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/238
=> site: import variables in site.overrides for correct overriding

{{cookiecutter.project_shortname}}/Dockerfile
=> dockerfile: add python3.9 image

{{cookiecutter.project_shortname}}/Pipfile
Please describe briefly your pull request.
**Reminder**
2. You agree that you have the right to license …
=> installation: bump invenio-app-rdm to v10.0.0.dev0

{{cookiecutter.project_shortname}}/invenio.cfg
Change the example order of S3 variables. It's more natural to put the secret after the key. This has burned me a few times.
**Reminder**
1. You license your contribution under the same terms as …
=> config: change S3 variable order

{{cookiecutter.project_shortname}}/assets/templates/custom_fields/.gitkeep
- closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/225
=> custom fields: add templates folder

{{cookiecutter.project_shortname}}/invenio.cfg
Fix broken link
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> Fix flask-babel link

{{cookiecutter.project_shortname}}/static/robots.txt
* closes: inveniosoftware/invenio-app-rdm#1937
=> Robots: add robots.txt

{{cookiecutter.project_shortname}}/app_data/pages/.gitkeep
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1934
=> templates: override invenio-pages default

.editorconfig, README.rst, cookiecutter.json, hooks/post_gen_project.sh, {{cookiecutter.project_shortname}}/Dockerfile, {{cookiecutter.project_shortname}}/Pipfile, {{cookiecutter.project_shortname}}/site/.gitkeep, {{cookiecutter.project_shortname}}/site/pyproject.toml, {{cookiecutter.project_shortname}}/site/setup.cfg, {{cookiecutter.project_shortname}}/site/setup.py, {{cookiecutter.project_shortname}}/site/tests/.gitkeep, {{cookiecutter.project_shortname}}/site/{{cookiecutter.package_name}}/assets/semantic-ui/js/{{cookiecutter.package_name}}/.gitkeep, {{cookiecutter.project_shortname}}/site/{{cookiecutter.package_name}}/assets/semantic-ui/less/{{cookiecutter.package_name}}/.gitkeep, {{cookiecutter.project_shortname}}/site/{{cookiecutter.package_name}}/templates/semantic-ui/{{cookiecutter.package_name}}/.gitkeep, {{cookiecutter.project_shortname}}/site/{{cookiecutter.package_name}}/views.py, {{cookiecutter.project_shortname}}/site/{{cookiecutter.package_name}}/webpack.py
requires https://github.com/inveniosoftware/invenio-cli/pull/322
=> Poc custom code

{{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf
closes https://github.com/inveniosoftware/helm-invenio/issues/47
=> nginx: added robots.txt rule

cookiecutter.json, {{cookiecutter.project_shortname}}/Dockerfile, {{cookiecutter.project_shortname}}/Pipfile
* changes Python version to 3.9, which is the version installed in Almalinux:1
* closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/238
=> docker: change base image to almalinux

{{cookiecutter.project_shortname}}/docker/pgadmin/servers.json
The change from `_` to `-` was introduced in `docker-compose` `v2`
Change to be propagated to all instances.
=> pgadmin: replace _ with -

{{cookiecutter.project_shortname}}/README.md
Update containers command.
**Reminder**
2. You agree that you have the right to license your …
=> site: update containers command

{{cookiecutter.project_shortname}}/assets/js/invenio_app_rdm/overridableRegistry/mapping.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2018
* needs https://github.com/inveniosoftware/invenio-app-rdm/pull/2033
=> overridable: add overriden mapping

{{cookiecutter.project_shortname}}/invenio.cfg
Add the SITENAME variable, which is used in the header and now UI elements from https://github.com/inveniosoftware/invenio-rdm-records/pull/1641.
**Reminder**
1. You license your contribution …
=> cfg: add sitename variable

{{cookiecutter.project_shortname}}/Pipfile
It's raising a warning on latest versions of pip
=> pipfile: remove DB from extras

{{cookiecutter.project_shortname}}/Pipfile
* https://github.com/pypa/pipenv/issues/6173
=> fix: DataValidationError of pipenv

{{cookiecutter.project_shortname}}/Pipfile
> Please describe briefly your pull request.
Upgrade `invenio-app-rdm` version to `v13.0.0dev0`
**Frontend**
**Reminder** …
=> pipfile: upgrade invenio-app-rdm to v13 dev

run-tests.sh, scripts/wait-for-services.sh, {{cookiecutter.project_shortname}}/docker-compose.full.yml, {{cookiecutter.project_shortname}}/docker-compose.yml, {{cookiecutter.project_shortname}}/docker-services.yml
* add missing OPENSEARCH_INITIAL_ADMIN_PASSWORD env var see https://github.com/inveniosoftware/docker-services-cli/pull/41
* Update deprecated docker-compose command
* Remove deprecated docker "version"
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> Search: Bump OpenSearch to v2.16.0

{{cookiecutter.project_shortname}}/invenio.cfg
* closes inveniosoftware/invenio-app-rdm#2838
=> feat: display packages versions in administration panel

cookiecutter.json, run-tests.sh, scripts/wait-for-services.sh, {{cookiecutter.project_shortname}}/README.md, {{cookiecutter.project_shortname}}/docker-compose.full.yml, {{cookiecutter.project_shortname}}/docker-compose.yml, {{cookiecutter.project_shortname}}/docker-services.yml
- **search: remove deprecated ElasticSearch support**
- **search: remove deprecated OpenSearch1**
=> backport deprecation removal

{{cookiecutter.project_shortname}}/invenio.cfg
This PR adds the admin email to the cookicutter configuration. It also re-organizes some of the config so all the app-rdm variables are together and fixes a broken link.
**Reminder**
1. You license your …
=> cfg: add admin email and reorganize app-rdm section

{{cookiecutter.project_shortname}}/invenio.cfg
Add the configuration for the OAI email address. Without this noted in the config, it's really easy to have the default info@inveniosoftware.org address show up.
**Reminder**
1. You license your …
=> cfg: add oai email

{{cookiecutter.project_shortname}}/docker-services.yml
> Please describe briefly your pull request.
**Frontend**
**Reminder**
2. You agree that you have the right to license …
=> db: upgrade to postgres 14.13

{{cookiecutter.project_shortname}}/app_data/vocabularies/names.yaml
closes [2545 ](https://github.com/inveniosoftware/invenio-app-rdm/issues/2545)
**Reminder**
2. You agree …
=> Add missing id to reduced vocab

README.rst, cookiecutter.json
There are some unused variables like github_repo https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/217 which I have removed. I also cleaned up the README and pointed people to the documentation site so we don't have to maintain multiple lists of variables.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> Remove unneeded variables and clean up README

README.rst, cookiecutter.json, {{cookiecutter.project_shortname}}/app_data/vocabularies/names.yaml, {{cookiecutter.project_shortname}}/docker-services.yml, {{cookiecutter.project_shortname}}/docker/nginx/conf.d/default.conf, {{cookiecutter.project_shortname}}/invenio.cfg
I don't have write access, so this backports all the fixes from the merge party into v12.
**Reminder**
2. You agree that …
=> Backport fixes to V12.0
